name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
        fetch-depth: 0
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish package Britt2022.A.A
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Constraints
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Constraints/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.ConstructionHeuristic
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.ConstructionHeuristic/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Contexts
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Contexts/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.CrossJoinElements
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.CrossJoinElements/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.CrossJoins
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.CrossJoins/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Dependencies.Hl7.Fhir.R4.Model
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Dependencies.Hl7.Fhir.R4.Model/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Exports
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Exports/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.GS
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.GS/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.ILS
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.ILS/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.IndexElements
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.IndexElements/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.LAHC
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.LAHC/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Models
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Models/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.NeighbourhoodStructures
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.NeighbourhoodStructures/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.ObjectiveFunctions
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.ObjectiveFunctions/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.ParameterElements
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.ParameterElements/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.ResultElements
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.ResultElements/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Results
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Results/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.SA
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.SA/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Solutions
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Solutions/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.SolverConfigurations
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.SolverConfigurations/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Britt2022.A.A.StandaloneLocalSearches
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.StandaloneLocalSearches/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.VariableElements
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.VariableElements/bin/Release/*.nupkg
    - name: Publish package Britt2022.A.A.Variables
      run: dotnet nuget push ${{ github.workspace }}/${{ github.event.repository.name }}.Variables/bin/Release/*.nupkg
